//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class registroentrada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public registroentrada()
        {
            this.detalleentrada = new HashSet<detalleentrada>();
        }
    
        public int nroent { get; set; }
        public System.DateTime fecent { get; set; }
        public int codemp { get; set; }
        public int codprov { get; set; }
        public bool estent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleentrada> detalleentrada { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}
